FROM quay.io/wildfly/wildfly:26.1.3.Final-jdk11

ENV DB_HOST=postgres-service \
    DB_PORT=5432 \
    DB_NAME=monitoring_test \
    DB_USER=monitoring_app \
    DB_PASS=monitoring_pass_2026

USER root

# Copier le driver et déployer l'application sous le nom ROOT.war
COPY postgresql-42.7.3.jar /opt/jboss/wildfly/standalone/deployments/
COPY monitor-test.war /opt/jboss/wildfly/standalone/deployments/ROOT.war

# Ajuster les permissions
RUN chown -R jboss:jboss /opt/jboss/wildfly/standalone/deployments/

USER jboss

# Configurer la DataSource en utilisant des variables dynamiques WildFly/Java
RUN /opt/jboss/wildfly/bin/jboss-cli.sh --commands="embed-server --std-out=echo, /subsystem=datasources/data-source=MonitoringDS:add(jndi-name=java:jboss/datasources/MonitoringDS, connection-url=jdbc:postgresql://\${env.DB_HOST:postgres-service}:\${env.DB_PORT:5432}/\${env.DB_NAME:monitoring_test}, driver-name=postgresql-42.7.3.jar, user-name=\${env.DB_USER:monitoring_app}, password=\${env.DB_PASS:monitoring_pass_2026}, enabled=true)"

EXPOSE 8080 9990

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]