FROM quay.io/wildfly/wildfly:26.1.3.Final-jdk11

ENV DB_HOST=postgres_db \
    DB_PORT=5432 \
    DB_NAME=monitoring_test \
    DB_USER=monitoring_app \
    DB_PASS=monitoring_pass_2026

USER root

# Copie du driver PostgreSQL et de l'application dans le dossier de déploiement
COPY postgresql-42.7.3.jar /opt/jboss/wildfly/standalone/deployments/
COPY monitor-test.war /opt/jboss/wildfly/standalone/deployments/

RUN chown -R jboss:jboss /opt/jboss/wildfly/standalone/deployments/

USER jboss

EXPOSE 8080 9990

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]ss