apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: monitoring-app
type: Opaque
stringData:
  postgres-user: "monitoring_app"
  postgres-password: "monitoring_pass_2026"
  postgres-db: "monitoring_db"
