apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring-app
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'postgres'
        static_configs:
          - targets: ['postgres-service:9187'] 

      - job_name: 'monitor-test-app'
        metrics_path: '/metrics.jsp'  # <-- L'ancien /monitor-test/ a été supprimé
        static_configs:
          - targets: ['jboss-service:8080'] # <-- Le vrai nom du service K8s