apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: monitoring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472 # Requis pour que Grafana ait les droits d'écriture sur le volume persistant
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          volumeMounts:
            # 1. Le montage de ton volume persistant d'origine
            - name: grafana-storage
              mountPath: /var/lib/grafana
            # 2. Le montage du fichier de configuration du provider
            - name: grafana-dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards
            # 3. Le montage du dossier contenant ton dashboard en format JSON
            - name: grafana-dashboards
              mountPath: /etc/grafana/dashboards
      volumes:
        # 1. Ton volume persistant d'origine
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc
        # 2. Le volume lié au ConfigMap du provider
        - name: grafana-dashboard-provider
          configMap:
            name: grafana-dashboard-provider
        # 3. Le volume lié au ConfigMap de ton JSON
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring-app
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30030