apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring-app
data:
  promtail.yml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki-service:3100/loki/api/v1/push

    scrape_configs:
      - job_name: jboss-app-logs
        static_configs:
          - targets: [localhost]
            labels:
              job: jboss
              container: jboss
              __path__: /var/log/pods/monitoring-app_jboss-deployment-*/*/*.log