apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-deployment
  namespace: monitoring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.8.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3100
---
apiVersion: v1
kind: Service
metadata:
  name: loki-service
  namespace: monitoring-app
spec:
  type: ClusterIP
  selector:
    app: loki
  ports:
    - port: 3100
      targetPort: 3100
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail-daemonset
  namespace: monitoring-app
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
        - name: promtail
          image: grafana/promtail:2.8.2
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/etc/promtail/promtail.yml"
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
            - name: config-volume
              mountPath: /etc/promtail
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: promtail-config
        - name: varlogpods
          hostPath:
            path: /var/log/pods