{
 "title": "monitoring JBOSS App",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "traffic & HTTP Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "requests load (total)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(monitor_test_load_requests_total[5m])"
      }
     ]
    },
    {
     "title": "HTTP errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(monitor_test_http_errors_total[5m])"
      }
     ]
    }
   ]
  },
  {
   "title": "system resources & JVM Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(monitor_test_cpu_milliseconds_requested_total[5m])"
      }
     ]
    },
    {
     "title": "JVM Uptime",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "monitor_test_jvm_uptime_seconds"
      }
     ]
    },
    {
     "title": "Memory Usage %",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 23, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(monitor_test_jvm_memory_used_bytes / monitor_test_jvm_memory_max_bytes) * 100"
      }
     ]
    }
   ]
  },
  {
   "title": "DataBase",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL requests erors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "rate(monitor_test_db_errors_total[5m])"
      }
     ]
    },
    {
     "title": "inserted lines (total)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "monitor_test_db_rows_inserted_total"
      }
     ]
    }
   ]
  }
 ]
}